FROM mdillon/postgis:10-alpine
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=CTM_db
ENV PGDATA=/home/postgres/ctm_db

WORKDIR /app

COPY . /app

RUN mkdir /home/postgres
RUN chown postgres /home/postgres
#RUN su postgres -c /app/doc/run-as-postgres

#RUN echo "host all  all    0.0.0.0/0  trust" >> /home/postgres/ctm_db/pg_hba.conf


