FROM amazonlinux:2

ENV CTM_WEB_TOP_DIR=/app/web
ENV ANACONDA3_TOP_DIR=/usr/local/share/anaconda3

ENV CTM_IN_DOCKER='#'

WORKDIR /app

COPY . /app

COPY ./doc/ctm.conf /etc/httpd/conf.d/

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql yum perl 

RUN /app/setup/run-web-setup

RUN chown -R apache:apache /app/web/php && \
    chown -R apache:apache /app/web/perl && \
    chown -R apache:apache /app/web/result

CMD ["apachectl", "-D", "FOREGROUND"]

