/****

  ctm_region.js

****/

var CTM_tb={
"models": [
{'id':1,
     'name':'ALBACORE',
     'abb name':'albacore',
     'path name':'albacore',
     'model filename':'albacore.tar.gz',
     'description':'ALBACORE is a shear wave velocity model for offshore Southern California that images plate boundary deformation including both thickening and thinning of the crustal and mantle lithosphere at the westernmost edge of the North American continent. The Asthenospheric and Lithospheric Broadband Architecture from the California Offshore Region Experiment (ALBACORE) ocean bottom seismometer array, together with 65 stations of the onshore Southern California Seismic Network, was used to measure ambient noise correlation functions and Rayleigh wave dispersion curves which are inverted for 3-D shear wave velocities. The resulting velocity model defines the transition from continental lithosphere to oceanic, illuminating the complex history and deformation in the region',
     'description_brief':'ALBACORE is a shear wave velocity model for offshore Southern California that images plate boundary deformation including both thickening and thinning of the crustal and mantle lithosphere at the westernmost edge of the North American continent ...',
     'detail':'Depth:0 to 100km',
     'coordinates': [ {'lon':-116.847200,'lat':33.300000},
                      {'lon':-116.847200,'lat':32.700000},
                      {'lon':-124.047200,'lat':32.700000},
                      {'lon':-124.047200,'lat':33.000000},
                      {'lon':-124.647200,'lat':33.000000},
                      {'lon':-124.647200,'lat':33.600000},
                      {'lon':-123.447200,'lat':33.600000},
                      {'lon':-123.447200,'lat':33.900000},
                      {'lon':-123.147200,'lat':33.900000},
                      {'lon':-123.147200,'lat':34.200000},
                      {'lon':-121.347200,'lat':34.200000},
                      {'lon':-121.347200,'lat':34.500000},
                      {'lon':-120.447200,'lat':34.500000},
                      {'lon':-120.447200,'lat':34.800000},
                      {'lon':-118.947200,'lat':34.800000},
                      {'lon':-118.947200,'lat':34.500000},
                      {'lon':-118.647200,'lat':34.500000},
                      {'lon':-118.647200,'lat':34.200000},
                      {'lon':-118.047200,'lat':34.200000},
                      {'lon':-118.047200,'lat':33.900000},
                      {'lon':-117.447200,'lat':33.900000},
                      {'lon':-117.447200,'lat':33.600000},
                      {'lon':-117.147200,'lat':33.600000},
                      {'lon':-117.147200,'lat':33.300000} ],
     'color':'#008080'},
{'id':27,
     'name':'Wasatch Front Utah',
     'abb name':'wfcvm',
     'path name':'wfcvm',
     'model filename':'wfcvm.tar.gz',
     'map':'ucvm_utah',
     'description':'The Wasatch Front CVM consists of detailed, rule-based representations of the major populated sediment-filled basins, embedded in a 3D crust, over a variable depth Moho, over upper mantle velocities. The basins are parameterized as a set of objects and rules implemented in a computer code that generates seismic velocities and density at any desired point. The objects are stratigraphic surfaces constructed from geological, geophysical, and geotechnical data, and the rule is Faust’s relation Vp = k(da)1/6 where Vp is P-wave velocity, d is the maximum depth of burial of the sediments, a is the sediment age, and k is a constant. Age at any point in a basin can be interpolated from the surfaces. The constant k is calibrated for each surface by comparison to well sonic logs and seismic refraction surveys. Density is derived from Vp using a standard relation; density is used to find Poisson\'s ratio and Vs is calculated from the Vp and Poisson\'s ratio. The shallow basin velocities are directly constrained by geotechnical borehole logs and detailed surface site response unit mapping based on surface geology and Vs30 measurements',
     'description_brief':'The Wasatch Front CVM consists of detailed, rule-based representations of the major populated sediment-filled basins, embedded in a 3D crust, over a variable depth Moho, over upper mantle velocities. The basins are parameterized as a set of objects and rules implemented ...',
     'coordinates': [ {'lon':-112.699997,'lat':39.75},
                      {'lon':-112.699997,'lat':42},
                      {'lon':-111.5,'lat':42},
                      {'lon':-111.5,'lat':39.75} ],
     'color':'#CBC0FF'},
    ],
"maps": [
    {'id':1,
     'map name':'UCVM',
     'abb name':'ucvm',
     'path name':'ucvm',
     'map filename':'ucvm.e',
     'description':'UCVM Topography and Vs30 Coverage Region(Thompson 2022)',
     'coordinates': [
        {'lon':-129.25,'lat':41},
        {'lon':-117.4199,'lat':28.0268},
        {'lon':-110.3864,'lat':31.80259},
        {'lon':-121.5606,'lat':45.4670}
               ],
     'color':'#0000FF'},
    {'id':2,
     'map name':'UCVM UTAH',
     'abb name':'ucvm_utah',
     'path name':'ucvm_utah',
     'map filename':'ucvm_utah.e',
     'description':'UCVM Utah Topography and Vs30 Coverage Region(2006)',
     'coordinates': [
        {'lon':-116,'lat':35},
        {'lon':-116,'lat':44},
        {'lon':-108,'lat':44},
        {'lon':-108,'lat':35}
               ],
     'color':'#FF00FF'}
    ],
"fileformats": [
    {'id':1,
     'format name':'image',
     'suffix':'png',
     'description':'plot image in fixed discrete color scale'},
    {'id':2,
     'format name':'metadata',
     'suffix':'json',
     'description':'metadata describing the image and the binary image data'},
    {'id':3,
     'format name':'data',
     'suffix':'bin',
     'description':'binary image data'},
    {'id':4,
     'format name':'dataset',
     'suffix':'json',
     'description':'image data in triplets'},
    {'id':5,
     'format name':'material property data',
     'suffix':'json',
     'description':'material property'}
    ],
"zmodes": [
    {'id':1,
     'mode name':'Depth',
     'value':'d',
     'description':'0 at surface and positive depth value'},
    {'id':2,
     'mode name':'Elevation(km)',
     'value':'e',
     'description':'0 at sealevel and positive value toward the air and negative value toward the center of the earth'}
    ],
"Products": [
    {'id': 1,
     'product name': '0D Point',
     'description':'Material Properties are returned for the selected location'},
    {'id': 2,
     'product name': '1D Vertical Profile',
     'description':'3 Vertical profile(Vp, Vs, Rho) plots are produced for the selected location. The plot starts at Z start, ends at Z ends, and in Z step interval'},
    {'id': 3,
     'product name': '2D Vertical Cross Section',
     'description':'A Cross section of a selected property is produced between two selected points. The plot starts at Z start, ends at Z ends, and the interval is determined by the web service'},
    {'id': 3,
     'product name': '2D Horizontal Slice',
     'description':'A Horizontal slice of a selected property is produced in a area marked by the rectangle drawn with the depth or elevation supplied as Z, and the interval is determined by the web service.'}
 ],
"descript": [
    {'id':'lon','label':'lon','show':1,'descript':'Longitude'},
    {'id':'lat','label':'lat','show':1,'descript':'Latitude'},
    {'id':'Z','label':'Z','show':1,'descript':'Input Z<br>(elevation - meters above sea level. Positive numbers above sea-level)<br>(depth - meters below ground surface. Positive numbers below ground surface)'},
    {'id':'surf','label':'surf','show':1,'descript':'Surface elevation from sea level'},
    {'id':'vs30','label':'vs30','show':1,'descript':'vs30 value from Thompson 2022 map'},
    {'id':'crustal','label':'crustal','show':1,'descript':'crustal model'},
    {'id':'cr_vp','label':'cr_vp','show':0,'descript':'cr_vp'},
    {'id':'cr_vs','label':'cr_vs','show':0,'descript':'cr_vs'},
    {'id':'cr_rho','label':'cr_rho','show':0,'descript':'cr_rho'},
    {'id':'gtl','label':'gtl','show':1,'descript':'gtl'},
    {'id':'gtl_vp','label':'gtl_vp','show':0,'descript':'gtl_vp'},
    {'id':'gtl_vs','label':'gtl_vs','show':0,'descript':'gtl_vs'},
    {'id':'gtl_rho','label':'gtl_rho','show':0,'descript':'gtl_rho'},
    {'id':'cmb_algo','label':'cmb_algo','show':0,'descript':'cmb_algo'},
    {'id':'cmb_vp','label':'vp','show':1,'descript':'vp'},
    {'id':'cmb_vs','label':'vs','show':1,'descript':'vs'},
    {'id':'cmb_rho','label':'rho','show':1,'descript':'rho'},
    {'id':'Zmode','label':'zmode','show':0,'descript':'zmode'},
 ],
"1D model": [
    {'id': 1,
     'name':'1D',
     'abb name':'1d',
     'description': 'Southern California regional 1D model based on Hadley-Kanamori Model',
    },
    {'id': 2,
     'name':'BBP1D',
     'abb name': 'bbp1d',
     'description': 'Nortridge Region 1D Los Angeles Basin model used in SCEC Broadband Platform'
    },
    {'id': 3,
     'name':'SF1D',
     'abb name':'sf1d',
     'description': 'SFCVM Sierra Foothills 1D Velocity Model'
    }],

"references": [
{ 'type':'model','name': ['albacore'],
     'author': 'Bowden et al., (2016)',
     'ref': 'Bowden, D. C., Kohler, M. D., Tsai, V. C., & Weeraratne, D. S. (2016). Offshore southern California lithospheric velocity structure from noise cross-correlation functions. Journal of Geophysical Research, 121(5), 3415-3427. doi:10.1002/2016JB012919'
},
{ 'type':'model','name':['canvas'],
     'author':'Doody et al., (2023)',
     'ref':'Doody, C., Rodgers, A., Afanasiev, M., Boehm, C., Krischer, L., Chiang, A., & Simmons, N. (2023). CANVAS: An adjoint waveform tomography model of California and Nevada. Journal of Geophysical Research: Solid Earth, 128(12). https://doi.org/10.1029/2023JB027583'
}]

};

